# Generated by Django 5.1.6 on 2026-06-06 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('mock', '모의고사'), ('naesin', '내신')], db_index=True, max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='시험명')),
                ('grade', models.CharField(blank=True, default='', max_length=10, verbose_name='학년')),
                ('year', models.CharField(blank=True, default='', max_length=4, verbose_name='연도')),
                ('month', models.CharField(blank=True, default='', max_length=50, verbose_name='강')),
                ('school_grade', models.CharField(blank=True, default='', max_length=50, verbose_name='학교학년')),
                ('season', models.CharField(blank=True, default='', max_length=100, verbose_name='시험명/시즌')),
                ('category', models.CharField(blank=True, default='', max_length=50, verbose_name='카테고리')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '시험지',
                'verbose_name_plural': '시험지',
                'db_table': 'exam_paper',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('source', 'grade', 'year', 'month', 'school_grade', 'season', 'category'), name='exam_paper_identity')],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', '진행 중'), ('submitted', '제출됨'), ('graded', '채점 완료')], db_index=True, default='in_progress', max_length=12, verbose_name='상태')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='제출 시각')),
                ('correct_count', models.IntegerField(default=0, verbose_name='맞은 개수')),
                ('total_questions', models.IntegerField(default=0, verbose_name='전체 문항 수')),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_sessions_graded', to=settings.AUTH_USER_MODEL, verbose_name='채점자')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exam.exampaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '시험 세션',
                'verbose_name_plural': '시험 세션',
                'db_table': 'exam_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='마감일')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='배정자')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to=settings.AUTH_USER_MODEL, verbose_name='학생')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exam.exampaper')),
            ],
            options={
                'verbose_name': '시험 배정',
                'verbose_name_plural': '시험 배정',
                'db_table': 'exam_assignment',
                'ordering': ['-assigned_at'],
                'unique_together': {('paper', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='번호')),
                ('answer', models.CharField(blank=True, default='', max_length=50, verbose_name='정답')),
                ('qtype', models.CharField(blank=True, default='', max_length=100, verbose_name='유형')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.exampaper')),
            ],
            options={
                'verbose_name': '시험 문항',
                'verbose_name_plural': '시험 문항',
                'db_table': 'exam_question',
                'ordering': ['paper', 'number'],
                'unique_together': {('paper', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='번호')),
                ('qtype', models.CharField(blank=True, default='', max_length=100, verbose_name='유형')),
                ('student_choice', models.CharField(blank=True, default='', max_length=50, verbose_name='학생 답')),
                ('correct_answer', models.CharField(blank=True, default='', max_length=255, verbose_name='정답(스냅샷)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='정답 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.examsession')),
            ],
            options={
                'verbose_name': '시험 응답',
                'verbose_name_plural': '시험 응답',
                'db_table': 'exam_answer',
                'ordering': ['session', 'number'],
                'indexes': [models.Index(fields=['session', 'number'], name='exam_answer_session_9e3168_idx')],
                'unique_together': {('session', 'number')},
            },
        ),
    ]
