# Generated by Django 5.1.6 on 2026-06-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exampaper_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswer',
            name='flagged',
            field=models.BooleanField(default=False, verbose_name='오류표시'),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='is_correct2',
            field=models.BooleanField(default=False, verbose_name='2차 정답 여부'),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='second_choice',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='2차 학생 답'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='daily_goal',
            field=models.IntegerField(default=0, verbose_name='하루 목표 문항'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='correct_count2',
            field=models.IntegerField(default=0, verbose_name='2차 맞은 개수'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='round',
            field=models.IntegerField(default=1, verbose_name='회차'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='round2_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='2차 제출 시각'),
        ),
    ]
