# Generated by Django 5.1.6 on 2026-06-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_examanswer_flagged_examanswer_is_correct2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='explanation',
            field=models.TextField(blank=True, default='', verbose_name='상세 해설'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='ref_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='관련번호'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='지문/문제'),
        ),
    ]
