# Generated by Django 5.1.6 on 2026-06-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_examquestion_explanation_examquestion_ref_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='explanation_image',
            field=models.ImageField(blank=True, null=True, upload_to='exam/explain/%Y/%m/', verbose_name='해설 이미지'),
        ),
    ]
