# Generated by Django 5.1.6 on 2026-06-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_examquestion_explanation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='teacher_checked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='교사 확인'),
        ),
    ]
