# Generated by Django 5.1.6 on 2026-06-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_examsession_teacher_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='redblue_released',
            field=models.BooleanField(default=False, verbose_name='빨파정답 공개'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='redblue_released_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='빨파정답 공개 시각'),
        ),
    ]
