# Generated by Django 5.1.6 on 2026-06-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_examsession_redblue_released_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examassignment',
            name='daily_goal',
            field=models.IntegerField(blank=True, null=True, verbose_name='하루 목표 문항'),
        ),
    ]
