# Generated by Django 5.1.6 on 2026-06-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_examassignment_daily_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='range_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='재번호 끝'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='range_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='재번호 시작'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='type_tags',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='유형 태그'),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='source',
            field=models.CharField(choices=[('mock', '모의고사'), ('naesin', '내신'), ('mock_type', '유형별')], db_index=True, max_length=10),
        ),
    ]
