# Generated by Django 5.1.6 on 2026-06-02 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='단원명')),
                ('school', models.CharField(blank=True, default='', max_length=100, verbose_name='학교')),
                ('exam', models.CharField(blank=True, default='', max_length=100, verbose_name='시험')),
                ('grade', models.CharField(choices=[('초1', '초1'), ('초2', '초2'), ('초3', '초3'), ('초4', '초4'), ('초5', '초5'), ('초6', '초6'), ('중1', '중1'), ('중2', '중2'), ('중3', '중3'), ('고1', '고1'), ('고2', '고2'), ('고3', '고3'), ('기타', '기타')], default='기타', max_length=10, verbose_name='학년')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vocab_units', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '단어 단원',
                'verbose_name_plural': '단어 단원',
                'db_table': 'vocab_unit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VocabSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_only', models.BooleanField(default=False, verbose_name='별표만 훈련')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.IntegerField(default=0, verbose_name='획득 점수')),
                ('correct_count', models.IntegerField(default=0, verbose_name='맞은 개수')),
                ('total_count', models.IntegerField(default=0, verbose_name='출제 개수')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_sessions', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='vocab.vocabunit')),
            ],
            options={
                'verbose_name': '단어 세션',
                'verbose_name_plural': '단어 세션',
                'db_table': 'vocab_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VocabWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='색인')),
                ('word', models.CharField(max_length=200, verbose_name='단어')),
                ('meaning', models.TextField(verbose_name='해석')),
                ('sub_unit', models.CharField(blank=True, default='', max_length=100, verbose_name='단원(소단원)')),
                ('source', models.CharField(blank=True, default='', max_length=100, verbose_name='출처')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocab.vocabunit', verbose_name='단원')),
            ],
            options={
                'verbose_name': '단어',
                'verbose_name_plural': '단어',
                'db_table': 'vocab_word',
                'ordering': ['unit', 'index'],
            },
        ),
        migrations.CreateModel(
            name='VocabAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_value', models.CharField(blank=True, default='', max_length=200, verbose_name='학생 입력')),
                ('is_correct', models.BooleanField()),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('score_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='vocab.vocabsession')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.vocabword')),
            ],
            options={
                'verbose_name': '단어 시도',
                'verbose_name_plural': '단어 시도',
                'db_table': 'vocab_attempt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentWordStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_word_stars', to=settings.AUTH_USER_MODEL, verbose_name='학생')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='vocab.vocabword', verbose_name='단어')),
            ],
            options={
                'verbose_name': '별표 단어',
                'verbose_name_plural': '별표 단어',
                'db_table': 'vocab_word_star',
            },
        ),
        migrations.CreateModel(
            name='VocabAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='마감일')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocab_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='배정자')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_assignments', to=settings.AUTH_USER_MODEL, verbose_name='학생')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='vocab.vocabunit', verbose_name='단원')),
            ],
            options={
                'verbose_name': '단어 단원 배정',
                'verbose_name_plural': '단어 단원 배정',
                'db_table': 'vocab_assignment',
                'ordering': ['-assigned_at'],
                'unique_together': {('student', 'unit')},
            },
        ),
        migrations.AddIndex(
            model_name='vocabword',
            index=models.Index(fields=['unit', 'sub_unit'], name='vocab_word_unit_id_c46d50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vocabword',
            unique_together={('unit', 'index')},
        ),
        migrations.AddIndex(
            model_name='vocabattempt',
            index=models.Index(fields=['session', 'word'], name='vocab_attem_session_8c229f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentwordstar',
            index=models.Index(fields=['student', 'word'], name='vocab_word__student_5a0987_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentwordstar',
            unique_together={('student', 'word')},
        ),
    ]
