# Generated by Django 5.1.6 on 2026-06-03 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabsession',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='검수 완료'),
        ),
        migrations.AddField(
            model_name='vocabsession',
            name='mode',
            field=models.CharField(choices=[('practice', '연습'), ('test', '정식 시험')], default='practice', max_length=10, verbose_name='모드'),
        ),
        migrations.AddField(
            model_name='vocabsession',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vocabsession',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocab_sessions_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='검수자'),
        ),
        migrations.CreateModel(
            name='VocabRangeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_index', models.IntegerField(verbose_name='시작 번호')),
                ('end_index', models.IntegerField(verbose_name='끝 번호')),
                ('source_label', models.CharField(default='내신단어TEST', max_length=100, verbose_name='단어장 라벨')),
                ('question_count', models.IntegerField(default=40, verbose_name='문제 수')),
                ('time_limit_seconds', models.IntegerField(default=1200, verbose_name='제한시간(초)')),
                ('pass_threshold', models.IntegerField(default=90, verbose_name='합격 기준 점수')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocab_range_tests_made', to=settings.AUTH_USER_MODEL, verbose_name='배정자')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_range_tests', to=settings.AUTH_USER_MODEL, verbose_name='학생')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='range_tests', to='vocab.vocabunit', verbose_name='단원(내신 단어장)')),
            ],
            options={
                'verbose_name': '시험 범위',
                'verbose_name_plural': '시험 범위',
                'db_table': 'vocab_range_test',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vocabsession',
            name='range_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='vocab.vocabrangetest', verbose_name='시험 범위'),
        ),
        migrations.AddIndex(
            model_name='vocabrangetest',
            index=models.Index(fields=['student', 'is_active'], name='vocab_range_student_e0e9a6_idx'),
        ),
    ]
