# Generated by Django 5.1.6 on 2026-06-04 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_vocabsession_is_reviewed_vocabsession_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, unique=True, verbose_name='단어(소문자)')),
                ('meaning', models.TextField(verbose_name='뜻')),
                ('source', models.CharField(choices=[('db', '교재 단어DB'), ('ai', 'AI')], default='db', max_length=10, verbose_name='출처')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '사전 캐시',
                'verbose_name_plural': '사전 캐시',
                'db_table': 'vocab_dictionary_cache',
            },
        ),
        migrations.CreateModel(
            name='WordCardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, default='', verbose_name='설명')),
                ('start_index', models.IntegerField(default=1, verbose_name='시작 번호')),
                ('end_index', models.IntegerField(default=20, verbose_name='끝 번호')),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('published', '완성')], default='draft', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_card_sets', to=settings.AUTH_USER_MODEL, verbose_name='학생')),
            ],
            options={
                'verbose_name': '낱말카드 세트',
                'verbose_name_plural': '낱말카드 세트',
                'db_table': 'vocab_word_card_set',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WordCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='순번')),
                ('word', models.CharField(blank=True, default='', max_length=200, verbose_name='단어')),
                ('meaning', models.TextField(blank=True, default='', verbose_name='뜻')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='vocab.wordcardset', verbose_name='세트')),
            ],
            options={
                'verbose_name': '낱말카드',
                'verbose_name_plural': '낱말카드',
                'db_table': 'vocab_word_card',
                'ordering': ['card_set', 'index'],
            },
        ),
        migrations.AddIndex(
            model_name='wordcardset',
            index=models.Index(fields=['student', 'status'], name='vocab_word__student_a5ccd6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wordcard',
            unique_together={('card_set', 'index')},
        ),
    ]
