# Generated by Django 5.1.6 on 2026-06-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_dictionarycache_wordcardset_wordcard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, verbose_name='영어')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='매칭키(소문자)')),
                ('meaning', models.TextField(verbose_name='한글 뜻')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '사전 단어',
                'verbose_name_plural': '사전 단어',
                'db_table': 'vocab_dictionary_entry',
            },
        ),
    ]
