# Generated by Django 5.1.6 on 2026-06-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0004_dictionaryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabunit',
            name='category',
            field=models.CharField(choices=[('naesin', '내신 단어'), ('wordbook', '교재 단어장')], db_index=True, default='naesin', max_length=12, verbose_name='분류'),
        ),
    ]
