# Generated by Django 5.1.6 on 2026-06-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0007_vocabrangetest_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockVocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(db_index=True, verbose_name='학년')),
                ('year', models.PositiveSmallIntegerField(verbose_name='년도')),
                ('month', models.PositiveSmallIntegerField(verbose_name='월')),
                ('number', models.PositiveSmallIntegerField(verbose_name='문항번호')),
                ('word', models.CharField(max_length=200, verbose_name='단어')),
                ('word_key', models.CharField(db_index=True, max_length=200, verbose_name='매칭키')),
                ('meaning', models.TextField(verbose_name='의미')),
            ],
            options={
                'verbose_name': '모의고사 단어',
                'verbose_name_plural': '모의고사 단어',
                'db_table': 'vocab_mock_vocab',
            },
        ),
        migrations.RenameIndex(
            model_name='wordcardstar',
            new_name='vocab_wordc_student_c4b098_idx',
            old_name='vocab_wordc_student_idx',
        ),
        migrations.AddIndex(
            model_name='mockvocab',
            index=models.Index(fields=['grade', 'year', 'month', 'number'], name='vocab_mock__grade_1b0c35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mockvocab',
            unique_together={('grade', 'year', 'month', 'number', 'word_key')},
        ),
    ]
