# Generated by Django 5.1.6 on 2026-06-04 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, default='', max_length=100, verbose_name='학교')),
                ('unit', models.CharField(blank=True, default='', max_length=100, verbose_name='단원')),
                ('title', models.CharField(max_length=200, verbose_name='단원명')),
                ('grade', models.CharField(choices=[('초1', '초1'), ('초2', '초2'), ('초3', '초3'), ('초4', '초4'), ('초5', '초5'), ('초6', '초6'), ('중1', '중1'), ('중2', '중2'), ('중3', '중3'), ('고1', '고1'), ('고2', '고2'), ('고3', '고3'), ('기타', '기타')], default='기타', max_length=10, verbose_name='학년')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_summary_units', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '요약문 단원',
                'verbose_name_plural': '요약문 단원',
                'db_table': 'summary_unit',
                'ordering': ['-created_at'],
                'unique_together': {('school', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='SummarySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', '진행 중'), ('submitted', '채점 대기'), ('graded', '채점 완료')], db_index=True, default='in_progress', max_length=12, verbose_name='상태')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='제출 시각')),
                ('correct_count', models.IntegerField(default=0, verbose_name='맞은 개수')),
                ('total_blanks', models.IntegerField(default=0, verbose_name='전체 빈칸 수')),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_sessions_graded', to=settings.AUTH_USER_MODEL, verbose_name='채점자')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_sessions', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='summary.summaryunit')),
            ],
            options={
                'verbose_name': '요약문 세션',
                'verbose_name_plural': '요약문 세션',
                'db_table': 'summary_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SummaryProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='색인')),
                ('sub_unit', models.CharField(blank=True, default='', max_length=100, verbose_name='소단원')),
                ('sentence1_template', models.TextField(verbose_name='문장1(ⓐ 포함)')),
                ('sentence1_answer', models.CharField(max_length=200, verbose_name='정답 ⓐ')),
                ('korean1', models.CharField(blank=True, default='', max_length=200, verbose_name='한글뜻 ⓐ')),
                ('sentence2_template', models.TextField(verbose_name='문장2(ⓑ 포함)')),
                ('sentence2_answer', models.CharField(max_length=200, verbose_name='정답 ⓑ')),
                ('korean2', models.CharField(blank=True, default='', max_length=200, verbose_name='한글뜻 ⓑ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='summary.summaryunit', verbose_name='단원')),
            ],
            options={
                'verbose_name': '요약문 문항',
                'verbose_name_plural': '요약문 문항',
                'db_table': 'summary_problem',
                'ordering': ['unit', 'index'],
                'unique_together': {('unit', 'index')},
            },
        ),
        migrations.CreateModel(
            name='SummaryBlankAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank', models.CharField(choices=[('a', 'ⓐ'), ('b', 'ⓑ')], max_length=1, verbose_name='빈칸')),
                ('first_input', models.CharField(blank=True, default='', max_length=200, verbose_name='1차 입력')),
                ('first_auto_correct', models.BooleanField(default=False, verbose_name='1차 자동 정답')),
                ('korean_shown', models.BooleanField(default=False, verbose_name='한글뜻 노출')),
                ('second_input', models.CharField(blank=True, default='', max_length=200, verbose_name='2차 입력')),
                ('correct_answer', models.CharField(blank=True, default='', max_length=200, verbose_name='정답(스냅샷)')),
                ('admin_verdict', models.CharField(blank=True, choices=[('O', 'O'), ('X', 'X')], max_length=1, null=True, verbose_name='관리자 판정')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.summaryproblem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blank_answers', to='summary.summarysession')),
            ],
            options={
                'verbose_name': '요약문 빈칸 응답',
                'verbose_name_plural': '요약문 빈칸 응답',
                'db_table': 'summary_blank_answer',
                'ordering': ['session', 'problem__index', 'blank'],
                'indexes': [models.Index(fields=['session', 'problem'], name='summary_bla_session_0f8822_idx')],
                'unique_together': {('session', 'problem', 'blank')},
            },
        ),
        migrations.CreateModel(
            name='SummaryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='마감일')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='배정자')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_assignments', to=settings.AUTH_USER_MODEL, verbose_name='학생')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='summary.summaryunit', verbose_name='단원')),
            ],
            options={
                'verbose_name': '요약문 단원 배정',
                'verbose_name_plural': '요약문 단원 배정',
                'db_table': 'summary_assignment',
                'ordering': ['-assigned_at'],
                'unique_together': {('student', 'unit')},
            },
        ),
    ]
