# Generated by Django 5.1.6 on 2026-06-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarysession',
            name='end_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='끝 문항'),
        ),
        migrations.AddField(
            model_name='summarysession',
            name='start_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='시작 문항'),
        ),
    ]
