# Generated by Django 5.1.6 on 2026-05-16 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='코드')),
                ('name', models.CharField(max_length=100, verbose_name='배지명')),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(default='🏅', help_text='이모지 1개', max_length=10)),
                ('condition_type', models.CharField(help_text='word_combo / sentence_combo / perfect_count / login_streak / speed 등', max_length=30)),
                ('condition_value', models.IntegerField(help_text='해당 조건의 임계값')),
                ('order', models.IntegerField(default=0, help_text='리스트에서 표시 순서')),
            ],
            options={
                'verbose_name': '배지 정의',
                'verbose_name_plural': '배지 정의',
                'db_table': 'writing_achievement',
                'ordering': ['order', 'condition_value'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(default=0, verbose_name='누적 XP')),
                ('current_word_combo', models.IntegerField(default=0)),
                ('max_word_combo_ever', models.IntegerField(default=0)),
                ('current_sentence_combo', models.IntegerField(default=0)),
                ('max_sentence_combo_ever', models.IntegerField(default=0)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('login_streak_days', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='writing_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '학생 프로필 (게임화)',
                'verbose_name_plural': '학생 프로필 (게임화)',
                'db_table': 'writing_student_profile',
            },
        ),
        migrations.CreateModel(
            name='WritingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='단원명')),
                ('publisher', models.CharField(blank=True, max_length=50, verbose_name='출판사')),
                ('grade', models.CharField(choices=[('초1', '초1'), ('초2', '초2'), ('초3', '초3'), ('초4', '초4'), ('초5', '초5'), ('초6', '초6'), ('중1', '중1'), ('중2', '중2'), ('중3', '중3'), ('고1', '고1'), ('고2', '고2'), ('고3', '고3'), ('기타', '기타')], default='기타', max_length=10, verbose_name='학년')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_writing_units', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '영작 단원',
                'verbose_name_plural': '영작 단원',
                'db_table': 'writing_unit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.IntegerField(default=0, verbose_name='획득 점수')),
                ('perfect_sentences', models.IntegerField(default=0)),
                ('max_word_combo', models.IntegerField(default=0)),
                ('max_sentence_combo', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_sessions', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='writing.writingunit')),
            ],
            options={
                'verbose_name': '풀이 세션',
                'verbose_name_plural': '풀이 세션',
                'db_table': 'writing_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='문제 번호')),
                ('korean', models.TextField(verbose_name='한글 및 힌트')),
                ('english', models.TextField(verbose_name='영어 정답')),
                ('word_hints', models.JSONField(blank=True, default=list, help_text='AI 자동 생성. 형식: [{"word": "under", "meaning": "~아래에"}, ...]', verbose_name='단어별 한글뜻')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='writing.writingunit', verbose_name='단원')),
            ],
            options={
                'verbose_name': '영작 문제',
                'verbose_name_plural': '영작 문제',
                'db_table': 'writing_problem',
                'ordering': ['unit', 'index'],
                'unique_together': {('unit', 'index')},
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.achievement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '획득한 배지',
                'verbose_name_plural': '획득한 배지',
                'db_table': 'writing_student_achievement',
                'ordering': ['-earned_at'],
                'unique_together': {('student', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='WritingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_index', models.IntegerField(verbose_name='단어 순번 (0부터)')),
                ('input_value', models.CharField(max_length=200, verbose_name='학생 입력')),
                ('correct_answer', models.CharField(max_length=200, verbose_name='정답')),
                ('hint_level', models.IntegerField(choices=[(0, '힌트 없음'), (1, '한글뜻'), (2, '첫글자'), (3, '정답 공개')], default=0)),
                ('is_correct', models.BooleanField()),
                ('attempt_num', models.IntegerField(verbose_name='시도 회차 (1~3)')),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('score_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.writingproblem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='writing.writingsession')),
            ],
            options={
                'verbose_name': '단어 시도',
                'verbose_name_plural': '단어 시도',
                'db_table': 'writing_attempt',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'problem', 'word_index'], name='writing_att_session_25beaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnitAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='마감일')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='배정자')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_assignments', to=settings.AUTH_USER_MODEL, verbose_name='학생')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='writing.writingunit', verbose_name='단원')),
            ],
            options={
                'verbose_name': '단원 배정',
                'verbose_name_plural': '단원 배정',
                'db_table': 'writing_assignment',
                'ordering': ['-assigned_at'],
                'unique_together': {('student', 'unit')},
            },
        ),
    ]
