# Generated by Django 5.1.6 on 2026-05-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_seed_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingsession',
            name='time_bonus_earned',
            field=models.IntegerField(default=0, verbose_name='시간 보너스'),
        ),
        migrations.AddField(
            model_name='writingunit',
            name='target_seconds',
            field=models.IntegerField(blank=True, help_text='빈 값이면 자동 계산 (문제 수 × 30초)', null=True, verbose_name='목표 완료 시간(초)'),
        ),
    ]
