# Generated by Django 5.1.6 on 2026-05-20 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_writingsession_time_bonus_earned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=500, verbose_name='URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='신고 내용')),
                ('screen_state', models.JSONField(blank=True, default=dict, help_text='입력 상태/시도 횟수/현재 단어 인덱스 등 스냅샷', verbose_name='화면 상태')),
                ('status', models.CharField(choices=[('pending', '대기'), ('reviewing', '검토중'), ('fixed', '수정 완료'), ('dismissed', '해당 없음')], default='pending', max_length=20, verbose_name='상태')),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='관리자 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to='writing.writingproblem', verbose_name='문제')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to='writing.writingsession', verbose_name='세션')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writing_bug_reports', to=settings.AUTH_USER_MODEL, verbose_name='신고 학생')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to='writing.writingunit', verbose_name='단원')),
            ],
            options={
                'verbose_name': '버그 신고',
                'verbose_name_plural': '버그 신고',
                'db_table': 'writing_bug_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
