# Generated by Django 5.1.6 on 2026-05-29 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0006_session_view_mode_bugreport_xp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStudyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('target_problems', models.IntegerField(default=0, verbose_name='목표 문제 수')),
                ('target_minutes', models.IntegerField(default=0, verbose_name='목표 학습 분')),
                ('target_sessions', models.IntegerField(default=0, verbose_name='목표 완료 단원 수')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='지정 선생님')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to=settings.AUTH_USER_MODEL, verbose_name='학생')),
            ],
            options={
                'verbose_name': '일일 학습 목표',
                'verbose_name_plural': '일일 학습 목표',
                'db_table': 'writing_daily_goal',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
