# Generated by Django 5.1.6 on 2026-05-29 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0007_dailystudygoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingsession',
            name='live_input',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='writingsession',
            name='live_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='writing.writingproblem', verbose_name='지금 풀고 있는 문제'),
        ),
        migrations.AddField(
            model_name='writingsession',
            name='live_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writingsession',
            name='live_word_index',
            field=models.IntegerField(default=0),
        ),
    ]
