# Generated by Django 5.1.6 on 2026-05-29 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0008_writingsession_live_input_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='입장 코드')),
                ('status', models.CharField(choices=[('waiting', '대기 중'), ('active', '진행 중'), ('finished', '종료')], default='waiting', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_rooms', to='writing.writingunit')),
            ],
            options={
                'verbose_name': '대전 방',
                'verbose_name_plural': '대전 방',
                'db_table': 'writing_match_room',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('final_score', models.IntegerField(default=0)),
                ('final_rank', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='writing.writingsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='writing.matchroom')),
            ],
            options={
                'verbose_name': '대전 참가자',
                'verbose_name_plural': '대전 참가자',
                'db_table': 'writing_match_participant',
                'ordering': ['joined_at'],
                'unique_together': {('room', 'student')},
            },
        ),
    ]
