# Generated by Django 5.1.6 on 2026-05-29 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0009_matchroom_matchparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchparticipant',
            name='ai_difficulty',
            field=models.CharField(blank=True, choices=[('easy', '쉬움'), ('medium', '중간'), ('hard', '어려움')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='ai_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='is_ai',
            field=models.BooleanField(default=False, verbose_name='AI 참가자 여부'),
        ),
        migrations.AlterField(
            model_name='matchparticipant',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
