# Generated by Django 5.1.6 on 2026-05-29 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0010_matchparticipant_ai_difficulty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_index', models.IntegerField(default=0, verbose_name='현재 카드 0-based')),
                ('total', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_activity', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='writing.writingunit')),
            ],
            options={
                'verbose_name': '플래쉬카드 활동',
                'verbose_name_plural': '플래쉬카드 활동',
                'db_table': 'writing_flashcard_activity',
            },
        ),
    ]
