# Generated by Django 5.1.6 on 2026-06-06 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='반 이름')),
                ('weekday_time', models.CharField(blank=True, default='', max_length=100, verbose_name='요일시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to=settings.AUTH_USER_MODEL, verbose_name='담당 교사')),
            ],
            options={
                'verbose_name': '반',
                'verbose_name_plural': '반',
                'db_table': 'report_classroom',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, default='', max_length=50, verbose_name='학교')),
                ('school_grade', models.CharField(blank=True, default='', max_length=50, verbose_name='학교학년')),
                ('chatroom_name', models.CharField(blank=True, default='', max_length=200, verbose_name='카톡 단톡방명')),
                ('class_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='report.classroom', verbose_name='반')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_info', to=settings.AUTH_USER_MODEL, verbose_name='학생')),
            ],
            options={
                'verbose_name': '학생 정보',
                'verbose_name_plural': '학생 정보',
                'db_table': 'report_student_info',
            },
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='날짜')),
                ('weekday_time', models.CharField(blank=True, default='', max_length=100, verbose_name='요일시간')),
                ('attendance', models.CharField(blank=True, default='', max_length=50, verbose_name='출석')),
                ('grammar_summary_result', models.CharField(blank=True, default='', max_length=200, verbose_name='어법/요약문결과')),
                ('vocab_result', models.CharField(blank=True, default='', max_length=200, verbose_name='단어시험결과')),
                ('writing_result', models.CharField(blank=True, default='', max_length=200, verbose_name='영작시험결과')),
                ('reading_result', models.CharField(blank=True, default='', max_length=200, verbose_name='TEST결과')),
                ('hw1_rate', models.CharField(blank=True, default='', max_length=200, verbose_name='과제1달성률')),
                ('hw2_rate', models.CharField(blank=True, default='', max_length=200, verbose_name='과제2달성률')),
                ('hw_rank', models.CharField(blank=True, default='', max_length=50, verbose_name='숙제달성률 순위')),
                ('reading_hw1_result', models.TextField(blank=True, default='', verbose_name='독해과제1결과')),
                ('reading_hw2_result', models.TextField(blank=True, default='', verbose_name='독해과제2결과')),
                ('grammar_no', models.CharField(blank=True, default='', max_length=100, verbose_name='문법번호')),
                ('grammar_hw_result', models.TextField(blank=True, default='', verbose_name='문법과제결과')),
                ('today_reading1', models.CharField(blank=True, default='', max_length=200, verbose_name='오늘독해과제1')),
                ('today_reading2', models.CharField(blank=True, default='', max_length=200, verbose_name='오늘독해과제2')),
                ('next_reading1', models.TextField(blank=True, default='', verbose_name='다음독해과제1')),
                ('next_reading2', models.TextField(blank=True, default='', verbose_name='다음독해과제2')),
                ('next_grammar', models.TextField(blank=True, default='', verbose_name='다음문법과제')),
                ('vocab_book', models.CharField(blank=True, default='', max_length=200, verbose_name='단어장')),
                ('vocab_hw_start', models.CharField(blank=True, default='', max_length=100, verbose_name='단어 숙제 시작')),
                ('vocab_hw_end', models.CharField(blank=True, default='', max_length=100, verbose_name='단어 숙제 끝')),
                ('is_new_vocab', models.BooleanField(default=False, verbose_name='새 단어장')),
                ('teacher_comment', models.CharField(blank=True, default='', max_length=500, verbose_name='선생님의 한마디')),
                ('report_image', models.ImageField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='리포트 이미지')),
                ('report_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_records_created', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to=settings.AUTH_USER_MODEL, verbose_name='학생')),
            ],
            options={
                'verbose_name': '일일 학습기록',
                'verbose_name_plural': '일일 학습기록',
                'db_table': 'report_daily_record',
                'ordering': ['-date', 'student'],
                'indexes': [models.Index(fields=['date', 'student'], name='report_dail_date_108db8_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
