# Generated by Django 5.1.6 on 2026-06-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='attend_weekdays',
            field=models.CharField(blank=True, default='', help_text='예: 화목 / 월수금', max_length=20, verbose_name='수업 요일'),
        ),
    ]
