# Generated by Django 5.1.6 on 2026-06-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_studentinfo_attend_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='naesin_exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='내신 시험시작일'),
        ),
    ]
