# Generated by Django 5.1.6 on 2026-06-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_studentinfo_naesin_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='weekday_time',
            field=models.CharField(blank=True, default='', help_text='예: 월수금444시 — 정렬용', max_length=30, verbose_name='수업 요일·시간'),
        ),
    ]
