# Generated by Django 5.1.6 on 2026-05-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='학원이 재원생으로 인정한 경우 True. 재원생 메뉴 접근에 필요.', verbose_name='재원생 승인'),
        ),
        migrations.AddField(
            model_name='member',
            name='login_id',
            field=models.CharField(blank=True, help_text='학원이 등록한 재원생용 ID (영문/숫자). 일반 회원가입자는 이메일로 로그인.', max_length=50, null=True, unique=True, verbose_name='로그인 ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=150, verbose_name='이름'),
        ),
    ]
