# Generated by Django 5.1.6 on 2026-05-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_is_approved_member_login_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='리더보드/대전에서 표시될 별명. 비어있으면 로그인 ID로 표시.', max_length=30, verbose_name='별명'),
        ),
    ]
