# Generated by Django 5.1.6 on 2026-06-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_member_school_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='academy_access',
            field=models.CharField(choices=[('none', '접근 없음'), ('variant', '변형문제만'), ('full', '모고 전체')], default='none', help_text='외부 승인 계정용. none=접근X, variant=변형문제만, full=모고 전체. 관리자/학원운영자(is_staff·is_superuser·is_academy)는 이 값과 무관하게 항상 전체.', max_length=10, verbose_name='모고 데이터 접근범위'),
        ),
    ]
