# Generated by Django 5.1.6 on 2026-06-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_member_academy_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='academy_access',
            field=models.CharField(choices=[('none', '접근 없음'), ('variant_view', '변형문제 열람만'), ('variant_down', '변형문제 열람+다운로드'), ('full', '모고 전체')], default='none', help_text='외부/학원 계정용. none=접근X, variant_view=변형문제 열람만, variant_down=변형문제 열람+다운로드, full=모고 전체. 관리자(is_staff·is_superuser)는 이 값과 무관하게 항상 전체.', max_length=15, verbose_name='모고 데이터 접근범위'),
        ),
    ]
