# Generated by Django 5.1.6 on 2026-06-20 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_member_academy_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='current_session_key',
            field=models.CharField(blank=True, default='', help_text='단일 세션 제한 — 새 로그인 시 갱신, 로그아웃 시 초기화.', max_length=40, verbose_name='현재 세션 키'),
        ),
        migrations.AddField(
            model_name='member',
            name='max_allowed_ips',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = 무제한. 1 이상 설정 시 해당 수만큼의 IP에서만 로그인 가능.', verbose_name='최대 허용 IP 수'),
        ),
        migrations.CreateModel(
            name='IPAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 주소')),
                ('status', models.CharField(choices=[('login_ok', '로그인 성공'), ('login_fail', '로그인 실패'), ('ip_blocked', 'IP 차단'), ('session', '세션 접속')], default='session', max_length=20, verbose_name='상태')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='경로')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='브라우저')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='접속 시각')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_logs', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': 'IP 접속 기록',
                'verbose_name_plural': 'IP 접속 기록',
                'db_table': 'member_ip_access_log',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 주소')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='최초 접속')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='최근 접속')),
                ('access_count', models.PositiveIntegerField(default=1, verbose_name='접속 횟수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_ips', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '허용 IP',
                'verbose_name_plural': '허용 IP 목록',
                'db_table': 'member_user_ip',
                'ordering': ['-last_seen'],
                'unique_together': {('user', 'ip_address')},
            },
        ),
    ]
