"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = False

ALLOWED_HOSTS = ['dprimeedu.synology.me', '127.0.0.1', 'localhost']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True
USE_X_FORWARDED_HOST = True
CSRF_TRUSTED_ORIGINS = ['https://dprimeedu.synology.me']
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.kakao',
    # 프로젝트 앱
    'config',
    'course.apps.CourseConfig',
    'member',
    'academy',
    'acad',
    'common',
    'writing',
    'vocab',
    'summary',
    'academy_tools',
    'exam',
    'report',
    'grammar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # GZip 압축 — HTML/CSS/JS 응답 크기 80~90% 감소
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'member.middleware.SingleSessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'config' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.context_processors.pending_badges',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'init_command': "PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL; PRAGMA cache_size=-64000; PRAGMA temp_store=MEMORY;",
            'timeout': 20,
        },
        'CONN_MAX_AGE': 600,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# 정적 파일 설정
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static"  # 프로젝트의 static 폴더
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 미디어 파일 설정
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 빨파 정답 PDF 루트 — nginx 컨테이너에 read-only 마운트된 '교재폴더' 경로(컨테이너 내).
# Django는 이 경로에서 파일 존재 여부만 확인하고, 실제 서빙은 X-Accel-Redirect 로
# nginx의 internal location(/redblue_internal/) 이 담당.
REDBLUE_ROOT = os.environ.get('REDBLUE_ROOT', '/redblue_root')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'member.Member'
AUTHENTICATION_BACKENDS = [
    'member.backends.LoginIdOrEmailBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# django.contrib.sites
SITE_ID = 1

# django-allauth 설정
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_ADAPTER = 'member.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'member.adapters.CustomSocialAccountAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = False

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID', ''),
            'secret': os.getenv('GOOGLE_SECRET', ''),
            'key': '',
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'kakao': {
        'APP': {
            'client_id': os.getenv('KAKAO_CLIENT_ID', ''),
            'secret': os.getenv('KAKAO_SECRET', ''),
            'key': '',
        },
    },
}

CSRF_COOKIE_HTTPONLY = True
CSRF_USE_SESSIONS = False
# 대용량 단원(수백 문제) admin 편집 허용
DATA_UPLOAD_MAX_NUMBER_FIELDS = 50000

# .pedu 보안 export 키 (base64, 32바이트씩).
# 운영에서는 반드시 .env 에 무작위 키를 지정. 부재 시 secure_export 모듈이
# 개발용 결정적 키로 폴백하므로 운영 부적합 — settings/.env 에 강제 등록 권장.
PEDU_AES_KEY = os.getenv('PEDU_AES_KEY', '')
PEDU_HMAC_KEY = os.getenv('PEDU_HMAC_KEY', '')

# 내신단어TEST 자동화 API 토큰 (개별단어장생성.py 연동)
VOCAB_IMPORT_TOKEN = os.getenv('VOCAB_IMPORT_TOKEN', 'pedu-vocab-2026')

# 요약문완성 자동화 API 토큰 (AI 자동화 요약문 생성 → 요약문웹동기화 연동)
SUMMARY_IMPORT_TOKEN = os.getenv('SUMMARY_IMPORT_TOKEN', 'pedu-summary-2026')

# 시험(내신 정답) import API 토큰 (내신웹업로드.py 연동)
EXAM_IMPORT_TOKEN = os.getenv('EXAM_IMPORT_TOKEN', 'pedu-exam-2026')

# 영작(writing) import API 토큰 (부교재 출력/AI 자동화 → 영작웹동기화 연동)
WRITING_IMPORT_TOKEN = os.getenv('WRITING_IMPORT_TOKEN', 'pedu-writing-2026')

# 어법(grammar) import API 토큰 (개별단어장생성 어법 → 어법웹동기화 연동)
GRAMMAR_IMPORT_TOKEN = os.getenv('GRAMMAR_IMPORT_TOKEN', 'pedu-grammar-2026')

# 일일리포트 카톡 페처 토큰 (회사 PC 카톡전송_웹.py 연동)
REPORT_KAKAO_TOKEN = os.getenv('REPORT_KAKAO_TOKEN', 'pedu-report-2026')
