# Generated by Django 5.1.6 on 2026-05-18 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalText_Data',
            fields=[
                ('index', models.CharField(db_column='Index', max_length=255)),
                ('additional_text', models.TextField(db_column='Additional_text')),
                ('pk_number', models.OneToOneField(db_column='PK_number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academy.keytable')),
            ],
            options={
                'db_table': 'Additional_text',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DescriptiveQuestion_Data',
            fields=[
                ('index', models.CharField(db_column='Index', max_length=255)),
                ('que_location', models.TextField(db_column='Que_Location')),
                ('ans_location', models.TextField(db_column='Ans_Location')),
                ('pk_number', models.OneToOneField(db_column='PK_number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academy.keytable')),
            ],
            options={
                'db_table': 'Descriptive_Question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailedExplanation_Data',
            fields=[
                ('index', models.CharField(db_column='Index', max_length=255)),
                ('saved_location', models.TextField(db_column='Saved_location')),
                ('pk_number', models.OneToOneField(db_column='PK_number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academy.keytable')),
            ],
            options={
                'db_table': 'DetailedExplanation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FillinBlank_Data',
            fields=[
                ('index', models.CharField(db_column='Index', max_length=255)),
                ('question', models.TextField(db_column='Question')),
                ('sentence', models.TextField(db_column='Sentence')),
                ('options', models.TextField(db_column='Options')),
                ('answer', models.TextField(db_column='Answer')),
                ('pk_number', models.OneToOneField(db_column='PK_number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academy.keytable')),
            ],
            options={
                'db_table': 'FillinBlank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grammarlv1_Data',
            fields=[
                ('index', models.CharField(db_column='Index', max_length=255)),
                ('question', models.TextField(db_column='Question')),
                ('answer', models.TextField(db_column='Answer')),
                ('pk_number', models.OneToOneField(db_column='PK_number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academy.keytable')),
            ],
            options={
                'db_table': 'Grammarlv1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grammarlv2_Data',
            fields=[
                ('index', models.CharField(db_column='Index', max_length=255)),
                ('question', models.TextField(db_column='Question')),
                ('answer', models.TextField(db_column='Answer')),
                ('pk_number', models.OneToOneField(db_column='PK_number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academy.keytable')),
            ],
            options={
                'db_table': 'Grammarlv2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grammarlv3_Data',
            fields=[
                ('index', models.CharField(db_column='Index', max_length=255)),
                ('question', models.TextField(db_column='Question')),
                ('answer', models.TextField(db_column='Answer')),
                ('pk_number', models.OneToOneField(db_column='PK_number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academy.keytable')),
            ],
            options={
                'db_table': 'Grammarlv3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModifiedQuestions_Data',
            fields=[
                ('index', models.CharField(db_column='Index', max_length=255)),
                ('question', models.TextField(db_column='Question')),
                ('qtype', models.TextField(db_column='Qtype')),
                ('sentence', models.TextField(db_column='Sentence')),
                ('option', models.TextField(db_column='Option')),
                ('answer', models.TextField(db_column='Answer')),
                ('modified', models.TextField(db_column='Modified')),
                ('pk_number', models.OneToOneField(db_column='PK_number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academy.keytable')),
            ],
            options={
                'db_table': 'Modified_Questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OriginalQuestion_Data',
            fields=[
                ('index', models.CharField(db_column='Index', max_length=255)),
                ('question', models.TextField(db_column='Question')),
                ('sentence', models.TextField(db_column='Sentence')),
                ('option', models.TextField(db_column='Option')),
                ('answer', models.TextField(db_column='Answer')),
                ('picture', models.TextField(db_column='Picture')),
                ('pk_number', models.OneToOneField(db_column='PK_number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academy.keytable')),
            ],
            options={
                'db_table': 'Original_Question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OriginalText_Data',
            fields=[
                ('index', models.CharField(db_column='Index', max_length=255)),
                ('origin_text', models.TextField(db_column='Origin_text')),
                ('pk_number', models.OneToOneField(db_column='PK_number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academy.keytable')),
            ],
            options={
                'db_table': 'Original_text',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionData',
            fields=[
                ('색인', models.CharField(db_column='색인', max_length=255, primary_key=True, serialize=False)),
                ('문제', models.TextField(db_column='문제')),
                ('유형', models.CharField(db_column='유형', max_length=100)),
                ('지문', models.TextField(db_column='지문')),
                ('보기', models.TextField(db_column='보기')),
                ('정답', models.CharField(db_column='정답', max_length=255)),
                ('변형', models.CharField(db_column='변형', max_length=100)),
                ('학년', models.CharField(db_column='학년', max_length=10)),
                ('연도', models.CharField(db_column='연도', max_length=4)),
                ('강', models.CharField(db_column='강', max_length=50)),
                ('번호', models.IntegerField(db_column='번호')),
                ('단원', models.CharField(db_column='단원', max_length=255)),
                ('그림', models.CharField(db_column='그림', max_length=255)),
            ],
            options={
                'db_table': 'question_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RedBlue_Data',
            fields=[
                ('index', models.CharField(db_column='Index', max_length=255)),
                ('origin_text', models.TextField(db_column='Origin_text')),
                ('red', models.TextField(db_column='Red')),
                ('blue', models.TextField(db_column='Blue')),
                ('answer', models.TextField(db_column='Ans_location')),
                ('pk_number', models.OneToOneField(db_column='PK_number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academy.keytable')),
            ],
            options={
                'db_table': 'RedBlue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolExamTest_Data',
            fields=[
                ('index', models.CharField(db_column='Index', max_length=255)),
                ('question', models.TextField(db_column='Question')),
                ('type', models.TextField(db_column='Type')),
                ('sentence', models.TextField(db_column='Sentence')),
                ('option', models.TextField(db_column='Option')),
                ('answer', models.TextField(db_column='Answer')),
                ('modified', models.TextField(db_column='Modified')),
                ('pk_number', models.OneToOneField(db_column='PK_number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academy.keytable')),
                ('pre_question', models.TextField(db_column='Pre_Question')),
            ],
            options={
                'db_table': 'SchoolExamtest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Summary_Data',
            fields=[
                ('index', models.CharField(db_column='Index', max_length=255)),
                ('origin_text', models.TextField(db_column='Origin_text')),
                ('red', models.TextField(db_column='Red')),
                ('blue', models.TextField(db_column='Blue')),
                ('summary', models.TextField(db_column='summary')),
                ('answer', models.TextField(db_column='Answer')),
                ('pk_number', models.OneToOneField(db_column='PK_number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academy.keytable')),
            ],
            options={
                'db_table': 'Summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Translation_Data',
            fields=[
                ('index', models.CharField(db_column='Index', max_length=255)),
                ('sentence', models.TextField(db_column='Sentence')),
                ('translation', models.TextField(db_column='Translation')),
                ('etc', models.TextField(db_column='ETC')),
                ('key_sentence', models.TextField(db_column='Key_sentence')),
                ('pk_number', models.OneToOneField(db_column='PK_number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academy.keytable')),
            ],
            options={
                'db_table': 'Translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WordTest_Data',
            fields=[
                ('index', models.CharField(db_column='Index', max_length=255)),
                ('word', models.TextField(db_column='word')),
                ('english_definition', models.TextField(db_column='english_definition')),
                ('korean_definition', models.TextField(db_column='korean_definition')),
                ('pk_number', models.OneToOneField(db_column='PK_number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academy.keytable')),
            ],
            options={
                'db_table': 'WordTest',
                'managed': False,
            },
        ),
    ]
