# Generated by Django 5.1.6 on 2026-05-18 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('academy_name', models.CharField(blank=True, max_length=255, null=True)),
                ('academy_address', models.CharField(blank=True, max_length=255, null=True)),
                ('academy_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('academy_email', models.EmailField(default='default@example.com', max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_img', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'academy',
            },
        ),
        migrations.CreateModel(
            name='AcademyAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KeyTable',
            fields=[
                ('pk_number', models.IntegerField(db_column='PK_number', primary_key=True, serialize=False)),
                ('total_number', models.TextField(db_column='Total_number')),
                ('grade', models.TextField(db_column='grade')),
                ('year', models.TextField(db_column='year')),
                ('month', models.TextField(db_column='month')),
                ('number', models.TextField(db_column='number')),
                ('qtype', models.TextField(db_column='Qtype')),
            ],
            options={
                'db_table': 'KEY_TABLE',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.IntegerField()),
                ('word_index', models.IntegerField()),
                ('input_value', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('attempt_num', models.IntegerField()),
                ('time_taken', models.IntegerField()),
                ('pk_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'translation_log',
            },
        ),
    ]
