# Generated by Django 5.1.6 on 2026-05-18 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_academy_academyadmin_category_keytable_event_review_and_more'),
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='admin',
            field=models.OneToOneField(blank=True, default=None, limit_choices_to={'member_type': 'academy_admin'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academyadmin',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.academy'),
        ),
        migrations.AddField(
            model_name='academyadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academy',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.category'),
        ),
        migrations.CreateModel(
            name='CountTable',
            fields=[
                ('table_name', models.TextField(db_column='Table_name')),
                ('pk_number', models.OneToOneField(db_column='PK_number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academy.keytable')),
                ('count', models.TextField(db_column='Count')),
            ],
            options={
                'db_table': 'Count_Table',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.academy'),
        ),
        migrations.AddField(
            model_name='review',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translationlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
