# Generated by Django 5.1.6 on 2026-05-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_academy_admin_academyadmin_academy_academyadmin_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='시작 시각')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 시각')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='소요(초)')),
                ('triggered_by', models.CharField(choices=[('cli', 'CLI'), ('web', '웹UI'), ('auto', '자동 (스케줄러)')], default='cli', max_length=20, verbose_name='트리거')),
                ('dry_run', models.BooleanField(default=False, verbose_name='드라이런')),
                ('target_grade', models.CharField(default='all', max_length=20, verbose_name='대상 학년')),
                ('target_sheet', models.CharField(default='all', max_length=50, verbose_name='대상 시트')),
                ('added', models.IntegerField(default=0, verbose_name='추가')),
                ('updated', models.IntegerField(default=0, verbose_name='수정')),
                ('skipped', models.IntegerField(default=0, verbose_name='변경없음/스킵')),
                ('errors', models.IntegerField(default=0, verbose_name='오류')),
                ('sheet_results', models.JSONField(blank=True, default=dict, help_text='{학년: {시트: {added, updated, skipped, error}}}', verbose_name='시트별 결과')),
                ('error_details', models.JSONField(blank=True, default=list, verbose_name='오류 상세')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
            ],
            options={
                'verbose_name': 'Sync 이력',
                'verbose_name_plural': 'Sync 이력',
                'ordering': ['-started_at'],
            },
        ),
    ]
