# Generated by Django 5.1.6 on 2026-05-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_synclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='keytable',
            name='book',
            field=models.CharField(blank=True, db_column='book', default='', max_length=255, verbose_name='교재명'),
        ),
        migrations.AddField(
            model_name='keytable',
            name='category',
            field=models.CharField(choices=[('mock_exam', '모의고사'), ('ebs_high3', 'EBS 고3'), ('ebs_naesin', 'EBS 내신교재'), ('textbook', '교과서')], db_column='category', default='mock_exam', max_length=20, verbose_name='카테고리'),
        ),
        migrations.AddIndex(
            model_name='keytable',
            index=models.Index(fields=['category', 'grade'], name='kt_cat_grade_idx'),
        ),
        migrations.AddIndex(
            model_name='keytable',
            index=models.Index(fields=['category', 'book'], name='kt_cat_book_idx'),
        ),
    ]
